services:
  db:
    container_name: db
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    image: api:latest
    build: .
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy
